
CREATE TABLE CINEMA (
	IdCinema VARCHAR(50) PRIMARY KEY,
	Indirizzo VARCHAR(50) NOT NULL UNIQUE,
	Provincia CHAR(2) NOT NULL,
	NumeroSala INTEGER NOT NULL,
	Città VARCHAR(50) NOT NULL,
	TELEFONO CHAR(10) NOT NULL UNIQUE,
	CONSTRAINT chk_telefono CHECK (TELEFONO not like '%[^0-9]%')
);

CREATE TYPE TECNOLOGIA AS ENUM ('IMAX','ISense','ScreenX','3D');
CREATE TYPE AUDIO AS ENUM ('Dolby Digital Surround','Doby Digital Plus');


CREATE TABLE SALA (
	IdSala VARCHAR(10) PRIMARY KEY,
	Capienza INTEGER NOT NULL,
	TECNOLOGIA TECNOLOGIA NOT NULL,
	AUDIO AUDIO NOT NULL,
	CONSTRAINT FOREIGN KEY (IdSala) REFERENCES CINEMA(IdCinema)
);

CREATE TABLE POSTO(
	IdPosto VARCHAR(10) PRIMARY KEY,
	PostoY INTEGER NOT NULL,
	FilaX CHAR(1) NOT NULL,
	Disponibile BOOLEAN NOT NULL
	CONSTRAINT FOREIGN KEY (IdPosto) REFERENCES SALA(IdSala)
);

CREATE TYPE GENERE AS ENUM ('Azione','Horror','Fantascienza','Comico','Thriller','Western','Documentario');


CREATE TABLE FILM (
	IdFilm VARCHAR(50) PRIMARY KEY,
	Titolo VARCHAR(50) NOT NULL UNIQUE,
	Trama VARCHAR(100) NOT NULL UNIQUE,
	Regia VARCHAR(50) NOT NULL,
	Anno DATE NOT NULL,
	Durata TIME NOT NULL,
	Genere GENERE NOT NULL,
	CONSTRAINT chk_anno CHECK (date_trunc('YEAR',Anno) = Anno)
);

CREATE TABLE PROIEZIONE(
	IdProiezione VARCHAR(50) PRIMARY KEY,
	Data DATE NOT NULL,
	OraInizio TIME NOT NULL,
	OraFine TIME NOT NULL,
	CONSTRAINT FOREIGN KEY (IdProiezione) REFERENCES FILM(IdFilm)
)
